# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "pipedrive-ruby"
  s.version = "0.3.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jan Schwenzien", "Waldemar Kusnezow", "Joel Courtney"]
  s.date = "2014-04-23"
  s.description = "Ruby wrapper for the Pipedrive API"
  s.email = "jan@general-scripting.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = `git ls-files`.split("\n")
  s.test_files = `git ls-files -- spec/*`.split("\n")
  s.homepage = "https://github.com/GeneralScripting/pipedrive-ruby.git"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Ruby wrapper for the Pipedrive API"

  s.add_runtime_dependency(%q<httparty>, [">= 0"])
  s.add_runtime_dependency(%q<json>, [">= 1.7.7"])
  s.add_runtime_dependency(%q<multi_xml>, [">= 0.5.2"])
  s.add_development_dependency(%q<test-unit>, [">= 3.2.5"])
  s.add_development_dependency(%q<webmock>, [">= 0"])
  s.add_development_dependency(%q<coveralls>, [">= 0"])
  s.add_development_dependency(%q<shoulda>, [">= 0"])
  s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
  s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
  s.add_development_dependency(%q<jeweler>, [">= 1.8.4"])
  s.add_development_dependency(%q<simplecov>, [">= 0"])
end
